export interface Currency {
  code: string;
  label: string;
}

/**
 * All Treasury-supported currencies, mirrored from currencies.json on the
 * backend. Each ISO 4217 code maps to the country_currency_desc value used
 * by the FiscalData API. Kept in sync manually — when adding a currency,
 * update both this file and the backend JSON.
 */
export const CURRENCIES: readonly Currency[] = [
  { code: 'AED', label: 'UAE Dirham' },
  { code: 'AFN', label: 'Afghan Afghani' },
  { code: 'ALL', label: 'Albanian Lek' },
  { code: 'AMD', label: 'Armenian Dram' },
  { code: 'ANG', label: 'Caribbean Guilder' },
  { code: 'AOA', label: 'Angolan Kwanza' },
  { code: 'ARS', label: 'Argentine Peso' },
  { code: 'AUD', label: 'Australian Dollar' },
  { code: 'AZN', label: 'Azerbaijani Manat' },
  { code: 'BAM', label: 'Bosnia-Herzegovina Marka' },
  { code: 'BBD', label: 'Barbadian Dollar' },
  { code: 'BDT', label: 'Bangladeshi Taka' },
  { code: 'BGN', label: 'Bulgarian Lev' },
  { code: 'BHD', label: 'Bahraini Dinar' },
  { code: 'BMD', label: 'Bermudian Dollar' },
  { code: 'BND', label: 'Brunei Dollar' },
  { code: 'BOB', label: 'Bolivian Boliviano' },
  { code: 'BRL', label: 'Brazilian Real' },
  { code: 'BSD', label: 'Bahamian Dollar' },
  { code: 'BWP', label: 'Botswana Pula' },
  { code: 'BYN', label: 'Belarusian Ruble' },
  { code: 'BZD', label: 'Belize Dollar' },
  { code: 'CAD', label: 'Canadian Dollar' },
  { code: 'CDF', label: 'Congolese Franc' },
  { code: 'CHF', label: 'Swiss Franc' },
  { code: 'CLP', label: 'Chilean Peso' },
  { code: 'CNY', label: 'Chinese Renminbi' },
  { code: 'COP', label: 'Colombian Peso' },
  { code: 'CRC', label: 'Costa Rican Colón' },
  { code: 'CUC', label: 'Cuban Convertible Peso' },
  { code: 'CUP', label: 'Cuban Peso' },
  { code: 'CVE', label: 'Cape Verdean Escudo' },
  { code: 'CZK', label: 'Czech Koruna' },
  { code: 'DJF', label: 'Djiboutian Franc' },
  { code: 'DKK', label: 'Danish Krone' },
  { code: 'DOP', label: 'Dominican Peso' },
  { code: 'DZD', label: 'Algerian Dinar' },
  { code: 'EGP', label: 'Egyptian Pound' },
  { code: 'ERN', label: 'Eritrean Nakfa' },
  { code: 'ETB', label: 'Ethiopian Birr' },
  { code: 'EUR', label: 'Euro' },
  { code: 'FJD', label: 'Fijian Dollar' },
  { code: 'GBP', label: 'British Pound' },
  { code: 'GEL', label: 'Georgian Lari' },
  { code: 'GHS', label: 'Ghanaian Cedi' },
  { code: 'GMD', label: 'Gambian Dalasi' },
  { code: 'GNF', label: 'Guinean Franc' },
  { code: 'GTQ', label: 'Guatemalan Quetzal' },
  { code: 'GYD', label: 'Guyanese Dollar' },
  { code: 'HKD', label: 'Hong Kong Dollar' },
  { code: 'HNL', label: 'Honduran Lempira' },
  { code: 'HTG', label: 'Haitian Gourde' },
  { code: 'HUF', label: 'Hungarian Forint' },
  { code: 'IDR', label: 'Indonesian Rupiah' },
  { code: 'ILS', label: 'Israeli Shekel' },
  { code: 'INR', label: 'Indian Rupee' },
  { code: 'IQD', label: 'Iraqi Dinar' },
  { code: 'IRR', label: 'Iranian Rial' },
  { code: 'ISK', label: 'Icelandic Króna' },
  { code: 'JMD', label: 'Jamaican Dollar' },
  { code: 'JOD', label: 'Jordanian Dinar' },
  { code: 'JPY', label: 'Japanese Yen' },
  { code: 'KES', label: 'Kenyan Shilling' },
  { code: 'KGS', label: 'Kyrgyzstani Som' },
  { code: 'KHR', label: 'Cambodian Riel' },
  { code: 'KMF', label: 'Comorian Franc' },
  { code: 'KRW', label: 'South Korean Won' },
  { code: 'KWD', label: 'Kuwaiti Dinar' },
  { code: 'KYD', label: 'Cayman Islands Dollar' },
  { code: 'KZT', label: 'Kazakhstani Tenge' },
  { code: 'LAK', label: 'Lao Kip' },
  { code: 'LBP', label: 'Lebanese Pound' },
  { code: 'LKR', label: 'Sri Lankan Rupee' },
  { code: 'LRD', label: 'Liberian Dollar' },
  { code: 'LSL', label: 'Lesotho Loti' },
  { code: 'LYD', label: 'Libyan Dinar' },
  { code: 'MAD', label: 'Moroccan Dirham' },
  { code: 'MDL', label: 'Moldovan Leu' },
  { code: 'MGA', label: 'Malagasy Ariary' },
  { code: 'MKD', label: 'Macedonian Denar' },
  { code: 'MMK', label: 'Myanmar Kyat' },
  { code: 'MNT', label: 'Mongolian Tögrög' },
  { code: 'MRU', label: 'Mauritanian Ouguiya' },
  { code: 'MUR', label: 'Mauritian Rupee' },
  { code: 'MVR', label: 'Maldivian Rufiyaa' },
  { code: 'MWK', label: 'Malawian Kwacha' },
  { code: 'MXN', label: 'Mexican Peso' },
  { code: 'MYR', label: 'Malaysian Ringgit' },
  { code: 'MZN', label: 'Mozambican Metical' },
  { code: 'NAD', label: 'Namibian Dollar' },
  { code: 'NGN', label: 'Nigerian Naira' },
  { code: 'NIO', label: 'Nicaraguan Córdoba' },
  { code: 'NOK', label: 'Norwegian Krone' },
  { code: 'NPR', label: 'Nepalese Rupee' },
  { code: 'NZD', label: 'New Zealand Dollar' },
  { code: 'OMR', label: 'Omani Rial' },
  { code: 'PEN', label: 'Peruvian Sol' },
  { code: 'PGK', label: 'Papua New Guinean Kina' },
  { code: 'PHP', label: 'Philippine Peso' },
  { code: 'PKR', label: 'Pakistani Rupee' },
  { code: 'PLN', label: 'Polish Złoty' },
  { code: 'PYG', label: 'Paraguayan Guaraní' },
  { code: 'QAR', label: 'Qatari Riyal' },
  { code: 'RON', label: 'Romanian Leu' },
  { code: 'RSD', label: 'Serbian Dinar' },
  { code: 'RUB', label: 'Russian Ruble' },
  { code: 'RWF', label: 'Rwandan Franc' },
  { code: 'SAR', label: 'Saudi Riyal' },
  { code: 'SBD', label: 'Solomon Islands Dollar' },
  { code: 'SCR', label: 'Seychellois Rupee' },
  { code: 'SDG', label: 'Sudanese Pound' },
  { code: 'SEK', label: 'Swedish Krona' },
  { code: 'SGD', label: 'Singapore Dollar' },
  { code: 'SLE', label: 'Sierra Leonean Leone' },
  { code: 'SOS', label: 'Somali Shilling' },
  { code: 'SRD', label: 'Surinamese Dollar' },
  { code: 'SSP', label: 'South Sudanese Pound' },
  { code: 'STN', label: 'São Tomé Dobra' },
  { code: 'SYP', label: 'Syrian Pound' },
  { code: 'SZL', label: 'Swazi Lilangeni' },
  { code: 'THB', label: 'Thai Baht' },
  { code: 'TJS', label: 'Tajikistani Somoni' },
  { code: 'TMT', label: 'Turkmenistani Manat' },
  { code: 'TND', label: 'Tunisian Dinar' },
  { code: 'TOP', label: 'Tongan Paʻanga' },
  { code: 'TRY', label: 'Turkish Lira' },
  { code: 'TTD', label: 'Trinidad & Tobago Dollar' },
  { code: 'TWD', label: 'New Taiwan Dollar' },
  { code: 'TZS', label: 'Tanzanian Shilling' },
  { code: 'UAH', label: 'Ukrainian Hryvnia' },
  { code: 'UGX', label: 'Ugandan Shilling' },
  { code: 'UYU', label: 'Uruguayan Peso' },
  { code: 'UZS', label: 'Uzbekistani Som' },
  { code: 'VES', label: 'Venezuelan Bolívar' },
  { code: 'VND', label: 'Vietnamese Đồng' },
  { code: 'VUV', label: 'Vanuatu Vatu' },
  { code: 'WST', label: 'Samoan Tālā' },
  { code: 'XAF', label: 'Central African CFA Franc' },
  { code: 'XCD', label: 'East Caribbean Dollar' },
  { code: 'XOF', label: 'West African CFA Franc' },
  { code: 'YER', label: 'Yemeni Rial' },
  { code: 'ZAR', label: 'South African Rand' },
  { code: 'ZMW', label: 'Zambian Kwacha' },
  { code: 'ZWG', label: 'Zimbabwe Gold' },
];
