-- Purchase transactions stored in USD with NUMERIC(19,4) precision.
-- The id is generated by the database using gen_random_uuid() (built into
-- PostgreSQL since v13) so the application never has to invent identifiers.
CREATE TABLE purchase_transactions (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    description         VARCHAR(50)     NOT NULL,
    transaction_date    DATE            NOT NULL,
    purchase_amount_usd NUMERIC(19, 4)  NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT purchase_amount_positive CHECK (purchase_amount_usd > 0),
    CONSTRAINT description_not_blank    CHECK (length(btrim(description)) > 0)
);

CREATE INDEX purchase_transactions_date_idx
    ON purchase_transactions (transaction_date DESC);

-- Transactional outbox. Each domain event is inserted in the same DB
-- transaction as the aggregate that produced it; a scheduled relay later
-- publishes it to Kafka and flips the status to PUBLISHED. The `type`
-- column is the event-type discriminator (e.g. purchase.transaction.created)
-- so consumers and the relay can route a payload to the correct topic and
-- schema. The payload is stored as TEXT — the outbox is only ever read by
-- id and never queried by JSON content, so the cost of JSONB indexing and
-- driver-side custom converters is not warranted. Status values are
-- enforced by a CHECK constraint to keep the relay logic simple.
CREATE TABLE outbox_events (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_id  UUID         NOT NULL,
    type          VARCHAR(64)  NOT NULL,
    payload       TEXT         NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ,
    CONSTRAINT outbox_status_chk  CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT outbox_payload_chk CHECK (length(payload) > 0)
);

-- Partial index: keeps lookups by the relay cheap regardless of table size.
CREATE INDEX outbox_events_pending_idx
    ON outbox_events (created_at)
    WHERE status = 'PENDING';
